[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"

# Remappings
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/openzeppelin-contracts/lib/forge-std/src/"
]

# Optimizer
optimizer = true
optimizer_runs = 200

# Testing
fuzz = { runs = 256 }

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
